MK_CFG_DIR = /home/z/share/make_cfg
include $(MK_CFG_DIR)/make.defs

LIBNAME = ndbm
LIBVERSION=1
CSRC = ndbm.c

WARN +=
OPPFLAGS += 
DEPOBJS = 
LDFLAGS = 
LDLIBS = -lpthread

include $(MK_CFG_DIR)/make.rules
